
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference

version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build-frontend:
    docker:
      - image: cimg/node:19.8.1
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: frontend
      - run:
          name: Install dependencies
          command: |
            cd frontend
            yarn install
      - run:
          name: Build frontend
          command: |
            cd frontend
            yarn build
      - store_artifacts:
          path: |
            frontend/build
          destination: builds

  unit-test-backend:
    docker:
      - image: cimg/node:19.8.1
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: backend
      - run:
          name: Build backend
          command: yarn
      - run:
          name: Run test for the application
          # command: yarn --cwd backend test:unit
          command: yarn test:unit
      - run:
          name: Send coverage data to Coveralls
          command: |
            yarn --cwd backend coverage
      - store_artifacts:
          path: |
            backend/build
          destination: builds

workflows:
  version: 2
  build:
    jobs:
      - unit-test-backend
      # - build-frontend:
      #     filters:
      #       branches:
      #         only: main
